add support to send all request via forward proxy
coralogix/nodejs-coralogix-sdk pull request #19
Opened 2020-12-14 07:13 UTC by ronkorland

2020-12-16 11:19 UTC, EldarAliiev requested changes
Some tests are not passed, so we cannot merge without it.
The rest of code looks fine.
Another fix required: bump package version in package.json file, after that we will be able to merge and publish new version.

2020-12-16 15:56 UTC, ronkorland commented
> Some tests are not passed, so we cannot merge without it.
> The rest of code looks fine.
> Another fix required: bump package version in package.json file, after that we will be able to merge and publish new version.

@EldarAliiev I fixed the tests + bump the version + looks like the tests in `http.service.js` doesn't really check anything because the code in sync and finish before the next or error call

2020-12-17 10:39 UTC, EldarAliiev approved these changes

2020-12-17 10:40 UTC, merged

2020-12-17 10:54 UTC, EldarAliiev commented
Published in version 1.1.27